[build]
publish = "dist"
command = "npm run build"
functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Content-Security-Policy = "default-src 'self' blob: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https://api.mapbox.com https://cdn.sanity.io; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.mapbox.com https://cdn.sanity.io https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://identity.netlify.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://api.mapbox.com https://events.mapbox.com https://tiles.mapbox.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.sanity.io https://identity.netlify.com;"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
